# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TV-Guidance' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TV-Guidance
  pod "AlamofireImage"
  pod "ExpandableLabel"
  
  target 'TV-GuidanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TV-GuidanceUITests' do
    # Pods for testing
  end

end
